name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          enable-cache: true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: uv sync --extra docs --extra dev

      - name: Build Sphinx docs
        run: uv run sphinx-build -b html docs/source docs/build/html --keep-going -n -W

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html/

  deploy-docs:
    if: github.ref == 'refs/heads/main'
    needs: build-docs
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
